matrix:
  include:
    - dist: trusty
      if: tag IS NOT present
    - os: osx
      osx_image: xcode10.2
      if: tag IS present

language: node_js
node_js: "12"

script:
  - npm test

deploy:
  provider: script
  script: npm run dist
  on:
    branch: master
    tags: true
