matrix:
  include:
    - os: linux
      dist: trusty
      language: node_js
      node_js: "12"
      if: tag IS NOT present
    - os: osx
      osx_image: xcode10.2
      language: node_js
      node_js: "12"
      if: tag IS present

jobs:
  include:
    - stage: lint
      script: npm test
    - stage: deploy
      script: npm run dist

stages:
  - name: lint
    if: tag IS NOT present
  - name: deploy
    if: tag IS present
